dist: trusty
sudo: required
language: android

jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    organization: "gbaudic-github"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm i -g ionic cordova@8.0.0

install:
  - cd laChouetteAppli
  - npm install
  - ionic cordova platform rm android
  - ionic cordova platform add android
  
script:
  - cd .. && sonar-scanner
  - cd laChouetteAppli && ionic cordova build android --prod

 
