dist: trusty
sudo: required
language: node_js
node_js:
  - "node"
  - "lts/*"
jdk:
  - oraclejdk8

android:
  components:
    - build-tools-26.0.2
    - android-26

before_install:
  - npm i -g ionic cordova

install:
  - cd laChouetteAppli
  - npm install
  - ionic cordova platform rm android
  - ionic cordova platform add android
  
script:
  - ionic cordova build android --prod

cache:
  directories:
    - "node_modules"

