dist: trusty
sudo: required
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm cache clean
  - sudo npm i -g ionic cordova

install:
  - cd laChouetteAppli
  - npm install
  - ionic cordova platform rm android
  - ionic cordova platform add android
  
script:
  - ionic cordova build android --prod
  - sonar-scanner

cache:
  directories:
    - "node_modules"

addons:
  sonarcloud:
    organization: "gbaudic-github"
  