dist: trusty
sudo: required
language: android

jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    organization: "gbaudic-github"

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm i -g ionic cordova

install:
  - cd laChouetteAppli
  - npm install
  - sudo ionic cordova platform rm android
  - sudo ionic cordova platform add android
  
script:
  - sudo ionic cordova build android --prod
  - cd .. && sudo sonar-scanner

cache:
  directories:
    - "node_modules"
  
