dist: trusty
sudo: required
language: android
node_js:
  - "node"
  - "lts/*"
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm -y
  - sudo npm i -g ionic cordova

install:
  - cd laChouetteAppli
  - npm install
  - ionic cordova platform rm android
  - ionic cordova platform add android
  
script:
  - ionic cordova build android --prod

cache:
  directories:
    - "node_modules"

